## Write a Numpy program to compute the multiplication of two given matrixes

In [5]:

import numpy as np

y = [[10, 15], [25, 30]]
x = [[35, 40], [45, 50]]

result = np.dot(y, x)
  
print(result)

[[1025 1150]
 [2225 2500]]


## Write a NumPy program to compute the determinant of a given square array

In [14]:

from numpy import linalg as LA
a = np.array([[1, 2], [3, 4]])


print(a)
print(np.linalg.det(a))

[[1 2]
 [3 4]]
-2.0000000000000004


## Write a NumPy program to compute the cross product of two given vectors

In [18]:
x = [[2, 4], [6, 8]]
y = [[10, 12], [14, 16]]

result = np.cross(x, y)

print(result)


[-16 -16]


## Write a NumPy program to compute the condition number of a given matrix

In [19]:
x = np.array([[10,20],[30,40]])
result =  np.linalg.cond(x)

print(result)

[[10 20]
 [30 40]]
14.93303437365923


## Write a NumPy program to compute the inverse of a given matrix

In [20]:
y = np.array([[1,2],[3,4]])
result =  np.linalg.inv(y)

print(result)

[[-2.   1. ]
 [ 1.5 -0.5]]
